language: cpp
matrix:
  include:
  - os: linux
    env: CONFIG=Debug
  - os: linux
    env: CONFIG=Release
  - os: osx
    env: CONFIG=Debug
  - os: osx
    env: CONFIG=Release
compiler:
  - gcc
  - clang
sudo: false
dist: trusty
before_install:
  - pip install --user cpp-coveralls
before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIG} ..
script:
  - make
  - make test
after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"