version: "{build}"
os: Visual Studio 2015
platform:
  - x64
install:
  - git submodule update --init --recursive
configuration:
  - Debug
  - Release
clone_folder: C:\projects\playground
before_build:
  - cmd: cd C:\projects\playground
  - cmd: md build
  - cmd: cd build
  - cmd: set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..
build:
  project: C:\projects\playground\build\playground.sln
  parallel: true
