version: "{build}"
os:
  - Visual Studio 2017
  - Visual Studio 2015
platform:
  - Win32
  - x64
install:
  - git submodule update --init --recursive
configuration:
  - Debug
  - Release
before_build:
  - cmake -H. -Bbuild -A%PLATFORM%
build:
  project: build\playground.sln
  parallel: true
  verbosity: normal
test_script:
  - cd build
  - ctest -C %CONFIGURATION%